### ISSUE TITLE
Simplify sytax to be simple static method call

### ISSUE THREAD

**Issue by Omranic** [rinvex/country#12]
```php
$egypt = Country::find('EG');
```

Is much better than:
```php
$egypt = (new Country)->find('EG');
```

**Comment by cyb3r** [comment]
is keeping both `find` methods as an object method (backward compatibility) and static method (as a new feature)  a good idea? It can be done by `__callStatic()` I think.
Isn't it better?

```php
$egypt = Country::get('EG');
```

**Comment by Omranic** [comment]
Re-written from scratch, the new syntax is much more intuitive: 
![screenshot 2016-09-29 18 43 40](https://cloud.githubusercontent.com/assets/406705/18961854/1b1d1b6c-8677-11e6-9b28-1156d6f81d1b.png)
727de24179b55f81dd9f33c7a1fc424bc342c675
