### ISSUE TITLE
Convert countries.json into PHP file(s) for better performance

### ISSUE THREAD

**Issue by Omranic** [rinvex/country#14]
Reference: https://www.reddit.com/r/PHP/comments/51do0f/php_package_for_retrieving_country_details_with/

**Comment by Omranic** [comment]
After testing performance of small blobs, it's been clear that blobs under ~ 1mb is better performing on json compared to php arrays, and that's on the scale of memory footprint & processing time consumed, so we'll stick to json files at the moment!

**Comment by ragboyjr** [comment]
Was this test done with opcache on? I think the performance is a different story when you run php with opcache since it's able to skip on the file system hit and parsing step.
