### ISSUE TITLE
Package still being maintained?

### ISSUE THREAD

**Issue by joshbrw** [rinvex/country#57]
Hey,

I was just wondering if `rinvex/country` is still being actively maintained? If not, would you be interested in handing off maintenance to someone else?

**Comment by Omranic** [comment]
Yes, it's actively maintained. Have you checked the `develop` branch? 😉 
Latest commit d6619c4  6 days ago @Omranic Omranic Update composer config

**Comment by joshbrw** [comment]
Thanks. Could you please take a look at #56 when you get a chance? Thank you.
