### ISSUE TITLE
[Proposal] Currency Symbols

### ISSUE THREAD

**Issue by andrew-s** [rinvex/country#58]
Hi all,

It would be useful to return the currency symbol in Hex and/or Dec format - I'm not sure if there's an automated source/way of integration into the existing json files. My thoughts were for the currency object to look something like;

```
{
	"GBP": {
		"iso_4217_code": "GBP",
		"iso_4217_numeric": 826,
		"iso_4217_name": "Pound sterling",
		"iso_4217_minor_unit": 2,
		"symbols": {
			"hex": "xa3",
			"dec": 163
		}
	}
}
```

**Comment by Omranic** [comment]
Any reference with good explanation?

**Comment by andrew-s** [comment]
The xe site has a pretty good list of currencies, their symbols and respective properties; [http://www.xe.com/symbols.php](http://www.xe.com/symbols.php)

**Comment by Omranic** [comment]
Well, while it may be useful for some people to add such info, but it still very small percentage who'd get benefit from it in my opinion. Additionally it's out of this package's scope. We've plans for a separate `rinvex/currency` package, but still no ETA..
