### ISSUE TITLE
Add a migration & seed maybe?

### ISSUE THREAD

**Issue by ionut-tanasa** [rinvex/country#7]
Could be cool to have this as a migration / seed.

**Comment by Omranic** [comment]
Cool idea, considered for implementation.
I'm thinking of a way to allow both ways of usage, static file & DB table.. 
Please feel free to submit any suggestions you might have 😃

**Comment by Omranic** [comment]
This package will be kept framework agnostic, and maybe soon we'll release a new Laravel specific package that provide both migrations & service for ease of use within Laravel apps 👍
