### ISSUE TITLE
addition of the nationality of the country (Egyptian nationality)

### ISSUE THREAD

**Issue by techpoints** [rinvex/country#76]
السلام عليكم
ياليت يتم إضافة جنسية الدولة مثل مصر تكون مصري

$egypt->getNativeNationalityName();
output : مصري

$egypt->getNationalityName();
output : Egyptian

**Comment by Omranic** [comment]
وعليكم السلام ورحمة الله وبركاته
لا يمكن إضافة هذه الخاصية لدولة واحدة أو مجموعة من الدول على حدى، إن كان بإمكانك إضافتها لجميع الدول بترجماتها وإرسالها فيسعدنى دمج التحديث :)

We can't just add demonym translations for only one or more countries, but if you can add such feature to all countries included in this package, I'll be happy to merge your pull request :)
